from __future__ import annotations

from enum import Enum


class FailureClass(str, Enum):
    PRODUCT_DEFECT = "PRODUCT_DEFECT"
    TEST_DEFECT = "TEST_DEFECT"
    MISSING_PREREQUISITE = "MISSING_PREREQUISITE"
    NON_HERMETIC_TEST = "NON_HERMETIC_TEST"
    DETERMINISTIC_RUNTIME_NOISE = "DETERMINISTIC_RUNTIME_NOISE"
    BASELINE_DEFECT = "BASELINE_DEFECT"
    CONTROLLER_DEFECT = "CONTROLLER_DEFECT"
    POLICY_DENIAL = "POLICY_DENIAL"
    EVIDENCE_INTEGRITY_FAILURE = "EVIDENCE_INTEGRITY_FAILURE"
    UNKNOWN = "UNKNOWN"


REPAIR_BUDGET_CLASSES = {FailureClass.PRODUCT_DEFECT}


def consumes_repair_budget(failure_class: FailureClass) -> bool:
    return failure_class in REPAIR_BUDGET_CLASSES
