from __future__ import annotations

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

from app.feedback.routes import router as feedback_router
from app.observability.audit import write_audit_event

from app.disputes.router import router as disputes_router
app = FastAPI(
    title="UPI Dispute Case Management",
    version="0.1.0",
    description="Mock-safe UPI dispute resolution case management application generated by a governed factory.",
)

app.include_router(feedback_router)
app.include_router(disputes_router)


@app.middleware("http")
async def add_trace_headers(request: Request, call_next):  # type: ignore[no-untyped-def]
    response = await call_next(request)
    response.headers["x-factory-mode"] = "local-production-disciplined"
    return response


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.get("/ready")
def ready() -> dict[str, str]:
    return {
        "status": "ready",
        "mode": "mock-safe-local",
        "real_payment_calls": "disabled",
    }


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    event_id = write_audit_event(
        action="unhandled_exception",
        target=str(request.url.path),
        result="ERROR",
        details={"error_type": type(exc).__name__},
    )
    return JSONResponse(
        status_code=500,
        content={"error": "internal_error", "audit_event_id": event_id},
    )
