#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import subprocess
import sys
from datetime import datetime, timezone
from typing import Any, Literal, TypedDict, cast

from langgraph.graph import END, StateGraph

APP_ID = "upi_dispute_resolution"
PHASE = "Phase 13S"
PHASE_ID = "phase13s_agent_owned_evidence_upload_validation"
BASELINE_TAG = "v0.13.17-governed-agentic-phase-runner"
PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[1]
ARTIFACT_DIR = (
    PROJECT_ROOT
    / "workspace"
    / "factory_generated"
    / APP_ID
    / "lifecycle_artifacts"
    / "phase13s"
)
GENERATED_ROOT = (
    PROJECT_ROOT
    / "workspace"
    / "factory_generated"
    / APP_ID
    / "generated_application"
    / "phase13s_evidence_upload_validation"
)
PACKAGE_DIR = GENERATED_ROOT / "phase13s_evidence_upload_validation_app"
AUDIT_PATH = ARTIFACT_DIR / "agent_owned_application_generation_audit.json"
MANIFEST_PATH = ARTIFACT_DIR / "agent_owned_application_generation_manifest.json"
REPORT_PATH = ARTIFACT_DIR / "agent_owned_application_generation_report.md"
TRACEABILITY_PATH = ARTIFACT_DIR / "requirement_traceability_matrix.json"
REQUIREMENT_PATH = ARTIFACT_DIR / "requirement_package.json"

ValidationStatus = Literal["not_started", "passed", "failed"]


class AgentAction(TypedDict):
    agent: str
    action: str
    status: str
    detail: str


class ValidationResult(TypedDict):
    command: list[str]
    return_code: int
    output_preview: str


class GeneratedFile(TypedDict):
    path: str
    purpose: str
    sha256: str


class PhaseState(TypedDict):
    app_id: str
    phase: str
    phase_id: str
    objective: str
    requirement_ids: list[str]
    generated_files: list[GeneratedFile]
    agent_actions: list[AgentAction]
    validation_results: list[ValidationResult]
    validation_status: ValidationStatus
    repair_attempts: int
    max_repair_attempts: int
    release_ready: bool
    status: str
    errors: list[str]


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def relative(path: pathlib.Path) -> str:
    return str(path.relative_to(PROJECT_ROOT))


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def write_file(path: pathlib.Path, content: str) -> GeneratedFile:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return {
        "path": relative(path),
        "purpose": "generated_by_phase13s_agentic_runner",
        "sha256": sha256_text(content),
    }


def add_action(state: PhaseState, agent: str, action: str, status: str, detail: str) -> None:
    state["agent_actions"].append(
        {"agent": agent, "action": action, "status": status, "detail": detail}
    )


def run_command(command: list[str], cwd: pathlib.Path) -> ValidationResult:
    result = subprocess.run(
        command,
        cwd=cwd,
        text=True,
        capture_output=True,
        check=False,
    )
    output = result.stdout + result.stderr
    return {
        "command": command,
        "return_code": result.returncode,
        "output_preview": output[:4000],
    }


def requirement_package_agent(state: PhaseState) -> PhaseState:
    next_state = state.copy()
    requirement = {
        "app_id": APP_ID,
        "phase": PHASE,
        "phase_id": PHASE_ID,
        "requirement_id": "REQ-13S-EVIDENCE-UPLOAD-VALIDATION",
        "title": "Generate UPI dispute evidence upload validation capability",
        "business_goal": (
            "Create a locally runnable generated capability that accepts dispute "
            "evidence metadata, validates deterministic constraints, and emits an "
            "auditable validation result."
        ),
        "scope": [
            "Pydantic request and response contracts",
            "Deterministic validation service",
            "Unit tests generated by the factory runner",
            "Traceability from requirement to code and tests",
            "Lifecycle evidence artifacts",
        ],
        "out_of_scope": [
            "Real NPCI, RBI, bank, PSP, or UPI rail integration",
            "Real document storage or malware scanning",
            "Real customer personally identifiable data ingestion",
        ],
        "truth_boundary": (
            "Primary generated UPI dispute capability is local and runnable. "
            "External ecosystem integrations remain simulated mocks only."
        ),
    }
    ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)
    REQUIREMENT_PATH.write_text(
        json.dumps(requirement, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    next_state["requirement_ids"] = [str(requirement["requirement_id"])]
    add_action(
        next_state,
        "requirement_package_agent",
        "normalize_requirement_package",
        "completed",
        "Requirement package for evidence upload validation was created.",
    )
    return next_state


def design_agent(state: PhaseState) -> PhaseState:
    next_state = state.copy()
    traceability = {
        "phase": PHASE,
        "phase_id": PHASE_ID,
        "mappings": [
            {
                "requirement_id": "REQ-13S-EVIDENCE-UPLOAD-VALIDATION",
                "design_elements": [
                    "EvidenceUploadRequest contract",
                    "EvidenceValidationResult contract",
                    "validate_evidence_upload service",
                ],
                "code_files": [
                    relative(PACKAGE_DIR / "contracts.py"),
                    relative(PACKAGE_DIR / "service.py"),
                ],
                "test_files": [
                    "tests/test_phase13s_agent_owned_application_generation.py"
                ],
                "evidence_files": [
                    relative(AUDIT_PATH),
                    relative(MANIFEST_PATH),
                    relative(REPORT_PATH),
                    relative(REQUIREMENT_PATH),
                ],
            }
        ],
    }
    TRACEABILITY_PATH.write_text(
        json.dumps(traceability, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    add_action(
        next_state,
        "design_agent",
        "create_traceable_design",
        "completed",
        "Design maps requirement to generated contracts, service, tests, and evidence.",
    )
    return next_state


def code_generation_agent(state: PhaseState) -> PhaseState:
    next_state = state.copy()
    generated_files = list(next_state["generated_files"])
    init_code = '''"""Generated Phase 13S evidence upload validation capability."""

from .contracts import EvidenceUploadRequest, EvidenceValidationResult
from .service import validate_evidence_upload

__all__ = [
    "EvidenceUploadRequest",
    "EvidenceValidationResult",
    "validate_evidence_upload",
]
'''
    contracts_code = '''from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator

EvidenceType = Literal[
    "customer_statement",
    "bank_statement",
    "upi_reference",
    "merchant_receipt",
]
UploaderType = Literal["customer", "operator", "bank_mock"]
ValidationStatus = Literal["ACCEPTED", "REJECTED"]


class EvidenceUploadRequest(BaseModel):
    """Local evidence metadata accepted by the generated dispute capability."""

    model_config = ConfigDict(extra="forbid")

    dispute_case_id: str = Field(min_length=3, max_length=64)
    transaction_id: str = Field(min_length=6, max_length=64)
    evidence_type: EvidenceType
    filename: str = Field(min_length=3, max_length=128)
    content_sha256: str = Field(min_length=64, max_length=64)
    content_size_bytes: int = Field(ge=1, le=5_000_000)
    uploaded_by: UploaderType
    notes: str | None = Field(default=None, max_length=500)

    @field_validator("content_sha256")
    @classmethod
    def sha256_must_be_hex(cls, value: str) -> str:
        lowered = value.lower()
        if len(lowered) != 64:
            raise ValueError("content_sha256 must be exactly 64 hex characters")
        if any(character not in "0123456789abcdef" for character in lowered):
            raise ValueError("content_sha256 must contain only hex characters")
        return lowered


class EvidenceValidationResult(BaseModel):
    """Deterministic local validation result for uploaded evidence metadata."""

    model_config = ConfigDict(extra="forbid")

    accepted: bool
    validation_status: ValidationStatus
    evidence_id: str
    dispute_case_id: str
    transaction_id: str
    risk_flags: list[str]
    audit_event_type: str
    audit_reference: str
'''
    service_code = '''from __future__ import annotations

import hashlib
from pathlib import PurePosixPath

from .contracts import EvidenceUploadRequest, EvidenceValidationResult

_ALLOWED_EXTENSIONS = {".pdf", ".png", ".jpg", ".jpeg", ".txt", ".json"}
_CUSTOMER_EVIDENCE_TYPES = {"customer_statement", "merchant_receipt", "upi_reference"}


def _stable_reference(*parts: str) -> str:
    joined = "|".join(parts)
    return hashlib.sha256(joined.encode("utf-8")).hexdigest()[:16].upper()


def _file_extension(filename: str) -> str:
    return PurePosixPath(filename).suffix.lower()


def validate_evidence_upload(
    request: EvidenceUploadRequest,
) -> EvidenceValidationResult:
    """Validate local evidence metadata without touching external systems."""

    risk_flags: list[str] = []
    extension = _file_extension(request.filename)
    if extension not in _ALLOWED_EXTENSIONS:
        risk_flags.append("UNSUPPORTED_FILE_EXTENSION")
    if request.uploaded_by == "customer" and request.evidence_type not in _CUSTOMER_EVIDENCE_TYPES:
        risk_flags.append("CUSTOMER_UPLOADED_NON_CUSTOMER_EVIDENCE_TYPE")
    if request.content_size_bytes < 128:
        risk_flags.append("SUSPICIOUSLY_SMALL_EVIDENCE_FILE")

    accepted = len(risk_flags) == 0
    reference = _stable_reference(
        request.dispute_case_id,
        request.transaction_id,
        request.filename,
        request.content_sha256,
    )
    return EvidenceValidationResult(
        accepted=accepted,
        validation_status="ACCEPTED" if accepted else "REJECTED",
        evidence_id=f"EVD-{reference}",
        dispute_case_id=request.dispute_case_id,
        transaction_id=request.transaction_id,
        risk_flags=risk_flags,
        audit_event_type="evidence_upload_validated",
        audit_reference=f"AUD-{reference}",
    )
'''
    readme_code = '''# Phase 13S Evidence Upload Validation Capability

This directory is generated by the governed agentic factory runner.

The capability is local and runnable. It validates UPI dispute evidence metadata
without calling real banks, NPCI, RBI, PSPs, payment rails, or upstream/downstream
external systems.
'''
    generated_files.extend(
        [
            write_file(PACKAGE_DIR / "__init__.py", init_code),
            write_file(PACKAGE_DIR / "contracts.py", contracts_code),
            write_file(PACKAGE_DIR / "service.py", service_code),
            write_file(GENERATED_ROOT / "README.md", readme_code),
        ]
    )
    next_state["generated_files"] = generated_files
    add_action(
        next_state,
        "code_generation_agent",
        "generate_application_capability_code",
        "completed",
        "Generated local evidence upload validation package files.",
    )
    return next_state


def test_generation_agent(state: PhaseState) -> PhaseState:
    next_state = state.copy()
    generated_files = list(next_state["generated_files"])
    test_code = '''from __future__ import annotations

import json
import os
import pathlib
import subprocess
import sys
from typing import Any, cast

from pydantic import ValidationError

PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[1]
GENERATED_ROOT = (
    PROJECT_ROOT
    / "workspace"
    / "factory_generated"
    / "upi_dispute_resolution"
    / "generated_application"
    / "phase13s_evidence_upload_validation"
)
ARTIFACT_DIR = (
    PROJECT_ROOT
    / "workspace"
    / "factory_generated"
    / "upi_dispute_resolution"
    / "lifecycle_artifacts"
    / "phase13s"
)


def run_phase13s_generation() -> dict[str, Any]:
    env = os.environ.copy()
    env["PYTHONPATH"] = ":".join(
        [
            str(PROJECT_ROOT / "src"),
            str(PROJECT_ROOT / "scripts"),
            str(PROJECT_ROOT),
            env.get("PYTHONPATH", ""),
        ]
    )
    result = subprocess.run(
        [
            sys.executable,
            str(PROJECT_ROOT / "scripts" / "run_phase13s_agent_owned_application_generation.py"),
        ],
        cwd=PROJECT_ROOT,
        env=env,
        text=True,
        capture_output=True,
        check=True,
    )
    return cast(dict[str, Any], json.loads(result.stdout))


def test_phase13s_agent_owned_generation_outputs_and_behavior() -> None:
    output = run_phase13s_generation()
    assert output["passed"] is True
    assert output["phase"] == "Phase 13S"
    assert output["graph_type"] == "StateGraph"
    assert output["release_ready"] is True

    sys.path.insert(0, str(GENERATED_ROOT))
    from phase13s_evidence_upload_validation_app import (  # pylint: disable=import-outside-toplevel
        EvidenceUploadRequest,
        validate_evidence_upload,
    )

    valid_request = EvidenceUploadRequest(
        dispute_case_id="CASE-13S-001",
        transaction_id="TXN-13S-000001",
        evidence_type="merchant_receipt",
        filename="receipt.pdf",
        content_sha256="a" * 64,
        content_size_bytes=2048,
        uploaded_by="customer",
    )
    result = validate_evidence_upload(valid_request)
    assert result.accepted is True
    assert result.validation_status == "ACCEPTED"
    assert result.evidence_id.startswith("EVD-")
    assert result.risk_flags == []

    rejected_request = valid_request.model_copy(update={"filename": "receipt.exe"})
    rejected = validate_evidence_upload(rejected_request)
    assert rejected.accepted is False
    assert rejected.validation_status == "REJECTED"
    assert "UNSUPPORTED_FILE_EXTENSION" in rejected.risk_flags

    with pytest_raises_validation_error():
        EvidenceUploadRequest(
            dispute_case_id="CASE-13S-001",
            transaction_id="TXN-13S-000001",
            evidence_type="merchant_receipt",
            filename="receipt.pdf",
            content_sha256="not-a-sha",
            content_size_bytes=2048,
            uploaded_by="customer",
        )

    traceability = json.loads(
        (ARTIFACT_DIR / "requirement_traceability_matrix.json").read_text(
            encoding="utf-8"
        )
    )
    mapping = traceability["mappings"][0]
    assert mapping["requirement_id"] == "REQ-13S-EVIDENCE-UPLOAD-VALIDATION"
    assert "contracts.py" in " ".join(mapping["code_files"])
    assert "tests/test_phase13s_agent_owned_application_generation.py" in mapping["test_files"]


class pytest_raises_validation_error:
    def __enter__(self) -> None:
        return None

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: object,
    ) -> bool:
        assert exc_type is not None
        assert issubclass(exc_type, ValidationError)
        return True
'''
    generated_files.append(
        write_file(
            PROJECT_ROOT / "tests" / "test_phase13s_agent_owned_application_generation.py",
            test_code,
        )
    )
    next_state["generated_files"] = generated_files
    add_action(
        next_state,
        "test_generation_agent",
        "generate_capability_tests",
        "completed",
        "Generated tests proving valid and rejected evidence upload behavior.",
    )
    return next_state


def docs_generation_agent(state: PhaseState) -> PhaseState:
    next_state = state.copy()
    generated_files = list(next_state["generated_files"])
    doc_code = '''# Phase 13S - Agent-Owned Application Capability Generation

Phase 13S is the first phase where the governed agentic runner owns generation
of a small real application capability.

## Generated capability

The generated capability validates UPI dispute evidence upload metadata.
It includes:

- Pydantic request and response contracts;
- deterministic local validation logic;
- generated behavioral tests;
- requirement-to-code-to-test traceability;
- lifecycle evidence artifacts.

## Governance boundary

The generated application capability is local and runnable. External banks,
NPCI-style systems, RBI-style systems, PSPs, UPI rails, document stores, malware
scanners, upstream applications, and downstream applications remain mock or
simulated boundaries only.

## Agent ownership

The Phase 13S runner uses LangGraph `StateGraph` agents for requirement package
normalization, design, code generation, test generation, documentation,
validation, bounded repair routing, and evidence persistence.
'''
    generated_files.append(
        write_file(
            PROJECT_ROOT
            / "docs"
            / "phase13s"
            / "agent_owned_application_capability_generation.md",
            doc_code,
        )
    )
    next_state["generated_files"] = generated_files
    add_action(
        next_state,
        "docs_generation_agent",
        "generate_operator_documentation",
        "completed",
        "Generated Phase 13S documentation with governance boundaries.",
    )
    return next_state


def validation_agent(state: PhaseState) -> PhaseState:
    next_state = state.copy()
    results = list(next_state["validation_results"])
    generated_python_files = [
        str(PACKAGE_DIR / "__init__.py"),
        str(PACKAGE_DIR / "contracts.py"),
        str(PACKAGE_DIR / "service.py"),
    ]
    results.append(run_command([sys.executable, "-m", "py_compile", *generated_python_files], PROJECT_ROOT))
    behavior_check = (
        "import sys; "
        f"sys.path.insert(0, {str(GENERATED_ROOT)!r}); "
        "from phase13s_evidence_upload_validation_app import "
        "EvidenceUploadRequest, validate_evidence_upload; "
        "request = EvidenceUploadRequest("
        "dispute_case_id='CASE-13S-001', transaction_id='TXN-13S-000001', "
        "evidence_type='merchant_receipt', filename='receipt.pdf', "
        "content_sha256='b' * 64, content_size_bytes=2048, uploaded_by='customer'); "
        "result = validate_evidence_upload(request); "
        "assert result.accepted is True and result.validation_status == 'ACCEPTED'"
    )
    results.append(run_command([sys.executable, "-c", behavior_check], PROJECT_ROOT))
    next_state["validation_results"] = results
    if all(result["return_code"] == 0 for result in results):
        next_state["validation_status"] = "passed"
        next_state["release_ready"] = True
        next_state["status"] = "awaiting_human_release_approval"
        add_action(
            next_state,
            "validation_agent",
            "validate_generated_capability",
            "completed",
            "Generated capability py_compile and behavior checks passed.",
        )
    else:
        next_state["validation_status"] = "failed"
        next_state["release_ready"] = False
        next_state["status"] = "needs_bounded_repair"
        next_state["errors"].append("Generated capability validation failed.")
        add_action(
            next_state,
            "validation_agent",
            "validate_generated_capability",
            "failed",
            "Generated capability validation failed and needs bounded repair.",
        )
    return next_state


def bounded_repair_agent(state: PhaseState) -> PhaseState:
    next_state = state.copy()
    next_state["repair_attempts"] += 1
    add_action(
        next_state,
        "bounded_repair_agent",
        "bounded_repair_not_required_or_escalated",
        "completed",
        "No generated-code repair was required in the successful path.",
    )
    return next_state


def evidence_agent(state: PhaseState) -> PhaseState:
    next_state = state.copy()
    add_action(
        next_state,
        "evidence_agent",
        "persist_lifecycle_evidence",
        "completed",
        "Persisted audit, manifest, report, and traceability evidence.",
    )
    audit: dict[str, Any] = {
        "app_id": APP_ID,
        "phase": PHASE,
        "phase_id": PHASE_ID,
        "generated_at_utc": utc_now(),
        "baseline_tag": BASELINE_TAG,
        "objective": next_state["objective"],
        "orchestration_framework": "langgraph",
        "graph_type": "StateGraph",
        "agent_actions": next_state["agent_actions"],
        "generated_files": next_state["generated_files"],
        "validation_results": next_state["validation_results"],
        "validation_status": next_state["validation_status"],
        "repair_attempts": next_state["repair_attempts"],
        "max_repair_attempts": next_state["max_repair_attempts"],
        "release_ready": next_state["release_ready"],
        "human_approval_required": True,
        "blocked_actions": ["git merge", "git push", "git tag", "release publish"],
        "requirement_ids": next_state["requirement_ids"],
        "status": next_state["status"],
        "passed": next_state["validation_status"] == "passed",
        "truth_boundary": (
            "Generated UPI dispute evidence upload validation capability is local "
            "and runnable; external ecosystem interfaces remain simulated mocks only."
        ),
    }
    ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)
    AUDIT_PATH.write_text(json.dumps(audit, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    MANIFEST_PATH.write_text(json.dumps(audit, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    REPORT_PATH.write_text(
        "# Phase 13S Agent-Owned Application Capability Generation\n\n"
        f"Status: `{audit['status']}`\n\n"
        f"Validation: `{audit['validation_status']}`\n\n"
        f"Generated files: `{len(next_state['generated_files'])}`\n\n"
        "The governed LangGraph runner generated a local evidence upload "
        "validation capability, tests, documentation, and traceability evidence.\n",
        encoding="utf-8",
    )
    return next_state


def should_repair(state: PhaseState) -> str:
    if state["validation_status"] == "passed":
        return "evidence_agent"
    if state["repair_attempts"] < state["max_repair_attempts"]:
        return "bounded_repair_agent"
    return "evidence_agent"


def build_graph() -> Any:
    graph = StateGraph(PhaseState)
    graph.add_node("requirement_package_agent", requirement_package_agent)
    graph.add_node("design_agent", design_agent)
    graph.add_node("code_generation_agent", code_generation_agent)
    graph.add_node("test_generation_agent", test_generation_agent)
    graph.add_node("docs_generation_agent", docs_generation_agent)
    graph.add_node("validation_agent", validation_agent)
    graph.add_node("bounded_repair_agent", bounded_repair_agent)
    graph.add_node("evidence_agent", evidence_agent)
    graph.set_entry_point("requirement_package_agent")
    graph.add_edge("requirement_package_agent", "design_agent")
    graph.add_edge("design_agent", "code_generation_agent")
    graph.add_edge("code_generation_agent", "test_generation_agent")
    graph.add_edge("test_generation_agent", "docs_generation_agent")
    graph.add_edge("docs_generation_agent", "validation_agent")
    graph.add_conditional_edges(
        "validation_agent",
        should_repair,
        {
            "bounded_repair_agent": "bounded_repair_agent",
            "evidence_agent": "evidence_agent",
        },
    )
    graph.add_edge("bounded_repair_agent", "validation_agent")
    graph.add_edge("evidence_agent", END)
    return graph.compile()


def initial_state(objective: str) -> PhaseState:
    return {
        "app_id": APP_ID,
        "phase": PHASE,
        "phase_id": PHASE_ID,
        "objective": objective,
        "requirement_ids": [],
        "generated_files": [],
        "agent_actions": [],
        "validation_results": [],
        "validation_status": "not_started",
        "repair_attempts": 0,
        "max_repair_attempts": 2,
        "release_ready": False,
        "status": "started",
        "errors": [],
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--objective",
        default="Generate UPI dispute evidence upload validation capability",
    )
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()
    graph = build_graph()
    state = cast(PhaseState, graph.invoke(initial_state(args.objective)))
    result = {
        "passed": state["validation_status"] == "passed",
        "phase": PHASE,
        "phase_id": PHASE_ID,
        "objective": state["objective"],
        "orchestration_framework": "langgraph",
        "graph_type": "StateGraph",
        "generated_app_dir": relative(GENERATED_ROOT),
        "generated_file_count": len(state["generated_files"]),
        "requirement_ids": state["requirement_ids"],
        "validation_status": state["validation_status"],
        "repair_attempts": state["repair_attempts"],
        "release_ready": state["release_ready"],
        "human_approval_required": True,
        "status": state["status"],
        "audit_path": relative(AUDIT_PATH),
        "traceability_path": relative(TRACEABILITY_PATH),
    }
    if not args.quiet:
        print(json.dumps(result, indent=2, sort_keys=True))
    if result["passed"] is not True:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
